export const SET_PLAYER_TYPE = "SET_PLAYER_TYPE"
export const SET_MOVES = "SET_MOVES"
export const SET_PLAYER_STATUS = "SET_PLAYER_STATUS"
export const SET_EXTERNAL_PLAYER = "SET_EXTERNAL_PLAYER"
export const SET_EXTERNAL_PLAYER_TESTURL = "SET_EXTERNAL_PLAYER_TESTURL"
export const SET_EXTERNAL_PLAYER_URL_TEST_RESULT = "SET_EXTERNAL_PLAYER_URL_TEST_RESULT"

export const START_GAME = "START_GAME"
export const GAME_OVER = "GAME_OVER"

export const ADD_MESSAGE = "ADD_MESSAGE"
export const CLEAR_MESSAGES = "CLEAR_MESSAGES"

