export const SET_PLAYER_TYPE = "SET_PLAYER_TYPE"
export const SET_PLAYER_STATUS = "SET_PLAYER_STATUS"

export const SET_URL_PLAYER = "SET_URL_PLAYER"
export const SET_URL_PLAYER_URL = "SET_URL_PLAYER_URL"
export const CLEAR_URL_PLAYER_TESTRESULT = "CLEAR_URL_PLAYER_TESTRESULT"

export const SET_CODE_PLAYER = "SET_CODE_PLAYER"
export const SET_CODE_PLAYER_CODE = "SET_CODE_PLAYER_CODE"
export const CLEAR_CODE_PLAYER_TESTRESULT = "CLEAR_CODE_PLAYER_TESTRESULT"
export const STORE_CODE_EDITOR_CODE = "STORE_CODE_EDITOR_CODE"

export const START_GAME = "START_GAME"
export const GAME_OVER = "GAME_OVER"

export const CLEAR_MESSAGES = "CLEAR_MESSAGES"
export const STORE_CANVAS = 'STORE_CANVAS'

// For running the UI without a server
export const TEST_START_GAME = "TEST_START_GAME"



